[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/app"
  to = "/signup"
  status = 302

[[redirects]]
  from = "/app/*"
  to = "/signup"
  status = 302

[[redirects]]
  from = "/login"
  to = "/signup"
  status = 302
